name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x, 22.x ]
    name: Ubuntu NodeJS ${{ matrix.node-version }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn ci
  build-windows:
    continue-on-error: true
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    name: Windows NodeJS ${{ matrix.node-version }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn ci
  verify-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    name: Verify NodeJS installation
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Verify install
        run: npm install "https://github.com/martijnversluis/ChordSheetJS/tree/$GITHUB_SHA"
