name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Enable Corepack
        run: corepack enable
      - name: Build
        run: yarn install && yarn build
      - name: Test
        run: cat lib/bundle.js
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: lib/bundle.js
